### ISSUE TITLE
宮城県公式新型コロナウイルス感染症関連情報のURLが異なっている

### ISSUE THREAD

**Issue by bapex** [code4shiogama/covid19-miyagi#2]
## 起こっている問題 / The Problem
- 宮城県公式新型コロナウイルス感染症関連情報のURLが異なっている
https://www.pref.miyagi.jp/soshiki/hohusom/covid-19.html

## スクリーンショット / Screenshot
<img width="1101" alt="スクリーンショット 2020-03-26 2 12 08" src="https://user-images.githubusercontent.com/19667736/77565351-6e0cac80-6f07-11ea-854c-7e1c4aac56ca.png">

## 期待する見せ方・挙動 / Expected Behavior

- おそらくこちらのリンクになると思います。（https://www.pref.miyagi.jp/site/covid-19/）

<img width="1093" alt="スクリーンショット 2020-03-26 2 12 14" src="https://user-images.githubusercontent.com/19667736/77565417-8da3d500-6f07-11ea-8ddc-c7ba0b3dd90b.png">

**Comment by code4shiogama** [comment]
ありがとうございます。
公式のURLが変更になっていました。現在は解決済みです。
