### ISSUE TITLE
陽性患者の属性 に「オープンデータを入手」が残っている

### ISSUE THREAD

**Issue by fu-sen** [code4shiogama/covid19-miyagi#5]
今のところ宮城県では関連情報をオープンデータ扱いで公表していないので、修正が必要です。

オープンデータみやぎ
https://www.pref.miyagi.jp/site/opendata-miyagi/

関連情報（Facebook 内 コメントを参照）
https://www.facebook.com/taisuke.fukuno/posts/10159628693988626

**Comment by code4shiogama** [comment]
データ自体は該当リンクから入手できるのでここは変更しない方針です。
