### ISSUE TITLE
2020年4月1日から4月6日にかけてのPCR検査実施件数が間違っている？

### ISSUE THREAD

**Issue by uribo** [code4shiogama/covid19-miyagi#7]
本来はデータを修正したPRを送るべきなのでしょうが、手順がわからなかったのでissueを上げておきます。

2020年4月1日から4月6日にかけてのPCR検査実施件数データに修正があったのか、県のウェブサイトからダウンロードできるデータと違いが生じています。

該当期間の `data/data.json` の値は以下ですが

https://github.com/code4shiogama/covid19-miyagi/blob/ce34186f32a2de96c26fe0495716d984b33889bc/data/data.json#L2489-L2494

`https://www.pref.miyagi.jp/uploaded/attachment/788176.xlsx` の同期間を見ると次のようになっています（スクリーンショットですみません）。

![image](https://user-images.githubusercontent.com/228649/79508160-f3513000-8073-11ea-80ec-62769ee38134.png)

**Comment by code4shiogama** [comment]
ご報告ありがとうございます。内容を確認したします

**Comment by satodainu** [comment]
データを修正しました。ご指摘ありがとうございます！
